repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/nedtaylor/fortran-format-hooks
    rev: 4ba1e56b2922879a794e39dc4f60fb7ccf05a0f2
    hooks:
    -   id: check-fortran-indentation
        args: [--line-length=80]
